name: Deploy to Live Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@stillwatersretreats.com '
            cd /home/ubuntu/stillwaters-website &&
            git pull origin main &&
            tmux send-keys -t 0 C-c &&
            tmux send-keys -t 0 "go run main.go" C-m &&
            sudo systemctl reload nginx
          '
